### ISSUE TITLE
Blue rail will not go up or down blocks like normal speed rail does. 

### ISSUE THREAD

**Issue by CosmicjLightning** [MC-U-Team/Useful-Railroads#1]
I;e place a blue rail then a block up and another rail, it won't connect like it's s'posed to.  Same goes for downward slopes. Also when you do fix that, a different mod had a problem which you might run into I'm not sure, is in order to go up the speed rail without the cart eventually turning around you have to push forward on the rail. Please make it so you don't have to do that, thank you. 
Also left you this in better detail on minecraft curseforge with some idea's for your mod. It's a good one so far, keep it up.

**Comment by HyCraftHD** [comment]
Thanks four your report. I'll however not change the current behaviour, because the carts will derail at fast speeds and i dont want to change minecrafts default behaviour too much. Use for slopes normal minecraft rails or other rail mods. I'll have a look at curseforge soon. Thanks anyways.
~Johannes

**Comment by CosmicjLightning** [comment]
Well that seems like an excuse to me to make it work properly. I had hoped you were different, sigh.

**Comment by HyCraftHD** [comment]
No, because it wouldn't make sense to me to have high speed rails go up in a 45° angel.

Please don't forget, you can always bring recommendations to mod authors but please don't be mad if they don't like it or won't implement it.
~Johannes

**Comment by Spongebobfan907** [comment]
> No, because it wouldn't make sense to me to have high speed rails go up in a 45° angel.
> 

can you make direction rails go up in a 45° angle

**Comment by HyCraftHD** [comment]
Please don't hop in other issues or feature requests that are closed for about half a year @Spongebobfan907
Create a new one
