### ISSUE TITLE
[MC-Version1.15.2] Can´t add blocks in to the "ground blocks" field of the track builders.

### ISSUE THREAD

**Issue by leoXplod** [MC-U-Team/Useful-Railroads#10]
**Describe the bug**
I can´t add any block in in to the "ground blocks" field in the track builders of the mod Useful Railroads.

**Versions**
- Minecraft Version: 1.15.2
- Forge Version: 31.0.14
- UTeamCore Version: 2.10.0.146

Other mods in the pack:
- Macaw´s bridges: 1.0.3
- Lightest lamps: 3.2.1
- Libnonymous: 1.1.0.2
- Tubes reloaded: 1.15.2-1.2.0
- Useful railroads: 1.3.0.17
- FastLeafDecay: v20
- Bonsai trees 2: 2.1.1.4
- Just Enough Items: 6.0.0.2

**Screenshots**

![2020-02-02_13 55 50](https://user-images.githubusercontent.com/60576682/73610946-a359e580-45bb-11ea-9918-817dba4f24f2.png)

**Comment by HyCraftHD** [comment]
The default ground blocks is gravel (kind of a reference to the real world gravel used under tracks).
You can add ground blocks with a datapack by overridding the ground_blocks.json tag file: https://github.com/MC-U-Team/Useful-Railroads/tree/1.15.2/src/generated/resources/data/usefulrailroads/tags/items/track_builder

**Comment by HyCraftHD** [comment]
Will close as this is not an issue

**Comment by leoXplod** [comment]
Hi, sorry for the delay. Thanks for your feedback. It worked!!!, my lack of attention hehe

**Comment by HyCraftHD** [comment]
No problem :) Glad it works now!
