### ISSUE TITLE
[1.16.3] Teleport rails, teleport you out of the cart

### ISSUE THREAD

**Issue by MarshMello0** [MC-U-Team/Useful-Railroads#21]
**Describe the bug**
Whenever you use the teleport rail, it teleports you outside of the minecart however you are still "connected" to it. When you shift-click to get out of the minecart after teleporting, it will teleport you to the minecarts current location.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a teleporting rail
2. Go through the teleporting rail like normal
3. Get teleported out of the mine cart

**Expected behaviour**
I would say you should stay inside of the minecart and both get teleported to continue riding.

**[Video on gfycat](https://gfycat.com/tastytendericterinewarbler)**

**Versions**
- Mod version: 1.4.4.31
- Minecraft version: 1.16.3
- Forge version: 34.1.10
- UTeamCore version: 3.1.9.181

**Comment by HyCraftHD** [comment]
Thanks for the report! I have a look at it soon!

EDIT:
 - Only 1.16.x is not working.
 - Only non interdimensional teleportation causes this bug.
 - Interdimensional teleportation seems to be spamming unknown passenger (no issue but would be nice if we can avoid that too)

**Comment by HyCraftHD** [comment]
Should be function again.
This message **Received passengers for unknown entity** is still there but it is not really worth to debug right now because that happens quite often in vanilla too and does not seem to cause any other issues
