### ISSUE TITLE
[1.16.4] Useful Railroads (usefulrailroads) encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by Zothen1973** [MC-U-Team/Useful-Railroads#23]
**Describe the bug**
Minecraft can't load mod together with several other mods.

The following errors appear in the crash log:
Failure message: Useful Railroads (usefulrailroads) encountered an error during the load_registries event phase
		java.lang.NoSuchFieldError: MISCELLANEOUS

**To Reproduce**
1. Install all mods I use ;)
2. Start Minecraft

**Expected behavior**
Minecraft loading into main menu without any errors

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77007295/104010702-37a9d080-51ad-11eb-84ba-94adaea7307c.png)

**Versions**
- Mod version: useful_railroads-1.16.4-1.4.6.34-dev.jar
- Minecraft version: 1.16.4
- Forge version: 35.1.28
- UTeamCore version: u_team_core-1.16.4-3.1.17.191.jar

**Log (if crash occures)**
[crash-2021-01-08_12.22.22-fml.txt](https://github.com/MC-U-Team/Useful-Railroads/files/5786902/crash-2021-01-08_12.22.22-fml.txt)

**Comment by HyCraftHD** [comment]
Seems like you are using the -dev Version. This version will only work inside a development workspace. Please use the normal one.

**Comment by Zothen1973** [comment]
How stupid of me, it works now. Thanks for your help!
