### ISSUE TITLE
build?

### ISSUE THREAD

**Issue by Redd56** [MC-U-Team/Useful-Railroads#3]
could ya build and upload the new hotfixed version?

**Comment by HyCraftHD** [comment]
https://minecraft.curseforge.com/projects/useful-railroads/files/2687894
Newest build on curseforge! Thanks for remembering me!

**Comment by Redd56** [comment]
yw, also i just realized the better railroad iron rails are about the same speed as the high speed rails, ima boost their speed up to 8 blocks a tick so its even more powerful.
