### ISSUE TITLE
1.16.4 - single track builder is not working

### ISSUE THREAD

**Issue by XKMR** [MC-U-Team/Useful-Railroads#32]
single track builder is not working

![screenshot](https://up.20script.ir/files/38ab-what.jpg " ")

**Versions**
- Mod version: 1.4.6.35
- Minecraft version: 1.16.4
- UTeamCore version: 3.1.17.192

**Comment by HyCraftHD** [comment]
Well what is not working?

**Comment by XKMR** [comment]
@HyCraftHD 
I tried shift + right-click but it didn't build anything.

**Comment by HyCraftHD** [comment]
Was there a chat message? There are probably to few blocks in the builder

**Comment by HyCraftHD** [comment]
Closing because no response. If you still have issues please reopen

**Comment by XKMR** [comment]
not enough blocks.

**Comment by HyCraftHD** [comment]
Then you need to add more blocks in the slots
