### ISSUE TITLE
[1.12.2] Teleport Rail causes server-side crash when linking

### ISSUE THREAD

**Issue by noobanidus** [MC-U-Team/Useful-Railroads#7]
This is due to [the call at line 44 to `EntityItem::getAge`](https://github.com/MC-U-Team/Useful-Railroads/blob/1.12.2/src/main/java/info/u_team/useful_railroads/item/ItemBlockRailTeleport.java#L44) which is actually a client-side only annotated function, despite the fact that the value is updated on the server side (which always seemed strange to me).

Unfortunately, I think your only option at this stage would be to use an access transformer (such as `public net.minecraft.entity.item.EntityItem field_70292_b # age`) to make the actual age field of the EntityItem public, allowing you to query that instead.

**Comment by HyCraftHD** [comment]
Thank you very much for the report and the pull. I'll merge it asap.

**Comment by HyCraftHD** [comment]
This is now uploaded on curseforge (1.12.2-1.1.1.9).
Thank you very much for the help.
~Johannes

**Comment by noobanidus** [comment]
No worries! If I notice anything else while playing around with the mod (or while people on my server are), I'll be sure to report it and submit a PR if it's something I can easily fix.
